name: Build and Upload Android Package Archive

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build (e.g., zlib, hello, android-shmem, all)'
        required: true
        default: 'all'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget unzip tar xz-utils

      # Ensure scripts are executable
      - name: Set script permissions
        run: |
          chmod +x prop.sh build.sh packages/*/build.sh

      # Run build.sh with user input
      - name: Build package
        run: |
          # Set PREFIX to a local directory to mimic Android path
          export PREFIX=$HOME/install/data/data/com.gebox.emu/files/usr/bionic
          sudo ./build.sh ${{ github.event.inputs.package }}

      # Create .tar.xz archive of /data/data/com.gebox.emu/files/
      - name: Create tar.xz archive
        run: |
          # Ensure the install directory exists
          if [ -d "$HOME/install/data/data/com.gebox.emu/files" ]; then
            # Create archive
           sudo tar -C $HOME/install -cJf ${{ github.event.inputs.package }}-files.tar.xz data/data/com.gebox.emu/files
          else
            echo "Error: Install directory $HOME/install/data/data/com.gebox.emu/files not found"
            exit 1
          fi

      # Upload .tar.xz artifact
      - name: Upload package archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package }}-files
          path: ${{ github.event.inputs.package }}-files.tar.xz
          if-no-files-found: error
